let officeTempArr = [
  {
    note: "One of your co-workers has gotten seriously ill. Because your company doesn’t offer sick days, everyone is contributing $20 to help her out.",
    optionOne: "PITCH IN",
    optionTwo: "SAY YOU FORGOT YOUR WALLET",
    optionThree: "",
    resultOne: "void 1",
    resultTwo: "void 2",
    resultThree: "void 3",
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 0,
    optionTwoMoneyAdded: 0,
    optionTwoMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 1,
  },
  {
    note: "A family friend sends your child a card. Inside is $10.",
    optionOne: "GIVE YOUR CHILD THE $10",
    optionTwo: "KEEP THE $10",
    optionThree: "",
    resultOne: "void que2 opt-1",
    resultTwo: "void que2 opt-2",
    resultThree: "void que2 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 0,
    optionTwoMoneyAdded: 10,
    optionTwoMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 2,
  },
  {
    note: "Your best friend from childhood is getting married, and they want you to be in the wedding. The only problem: It's in another state.",
    optionOne: "FLY TO THE WEDDING ($350)",
    optionTwo: "SAY YOU CAN'T GO",
    optionThree: "",
    resultOne: "SOME RESULT TEXT que-3 opt-1",
    resultTwo: "SOME RESULT TEXT que-3 opt-2",
    resultThree: "SOME RESULT TEXT que-3 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 350,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 3,
  },
  {
    note: "You've been putting off doing laundry for weeks because you don't have a washer or dryer.",
    optionOne: "GO TO THE LAUNDROMAT ($30)",
    optionTwo: "ASK A FRIEND",
    optionThree: "WEAR DIRTY CLOTHES",
    resultOne: "SOME RESULT TEXT que4 opt-1",
    resultTwo: "SOME RESULT TEXT que4 opt-2",
    resultThree: "SOME RESULT TEXT que4 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 30,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 4,
  },
  {
    note: "The local community college is offering an online course in computer science, which could be your ticket to a higher paycheck. But the class costs $200.",
    optionOne: "SIGN UP ($200)",
    optionTwo: "MAYBE NEXT SEMESTER",
    optionThree: "",
    resultOne: "SOME RESULT TEXT que5 opt-1",
    resultTwo: "SOME RESULT TEXT que5 opt-2",
    resultThree: "SOME RESULT TEXT que5 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 200,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 5,
  },
  {
    note: "You're sure you weren't speeding, but the cop who gave you a ticket disagrees.",
    optionOne: "PAY IT OFF ($250)",
    optionTwo: "CONTEST IT IN COURT",
    optionThree: "",
    resultOne: "SOME RESULT TEXT que6 opt-1",
    resultTwo: "SOME RESULT TEXT que6 opt-2",
    resultThree: "SOME RESULT TEXT que6 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 250,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 100,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 6,
  },
  {
    note: "Your bathroom sink has a small leak that just became a big leak. Your landlord won't return your calls, and you can't put it off any longer.",
    optionOne: "CALL A PLUMBER ($150)",
    optionTwo: "TRY TO FIX IT YOURSELF",
    optionThree: "",
    resultOne: "SOME RESULT TEXT que7 opt-1",
    resultTwo: "SOME RESULT TEXT que7 opt-2",
    resultThree: "SOME RESULT TEXT que7 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 150,
    optionTwoMoneyAdded: 0,
    optionTwoMoneyRemoved: 50,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 7,
  },
  {
    note: "One of your co-workers has gotten seriously ill. Because your company doesn't offer sick days, everyone is contributing $20 to help her out.",
    optionOne: "PITCH IN",
    optionTwo: "SAY YOU FORGOT YOUR WALLET",
    optionThree: "",
    resultOne: "SOME RESULT TEXT que8 opt-1",
    resultTwo: "SOME RESULT TEXT que8 opt-2",
    resultThree: "SOME RESULT TEXT que8 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 20,
    optionTwoMoneyAdded: 0,
    optionTwoMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 8,
  },
  {
    note: "You come out of your house to discover that someone has siphoned the gas from your car. And you're already running late for work.",
    optionOne: "TAKE THE BUS",
    optionTwo: "CALL IN SICK",
    optionThree: "ASK A FRIEND FOR A RIDE",
    resultOne: "SOME RESULT TEXT que9 opt-1",
    resultTwo:
      "BCOS YOU CALLED IN SICK $50 WAS REMOVED FROM YOUR PAY-CHEQUE que9 opt-2",
    resultThree: "SOME RESULT TEXT que9 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 15,
    optionTwoMoneyAdded: 0,
    optionTwoMoneyRemoved: 50,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 9,
  },
  {
    note: "The repetitive work you do is taking its toll. Your back hurts so badly you can barely stand, and it's only the beginning of your shift.",
    optionOne: "SUBMIT A WORKER'S COMP CLAIM",
    optionTwo: "WORK THROUGH THE PAIN",
    optionThree: "TAKE THE DAY OFF",
    resultOne: "SOME RESULT TEXT que10 opt-1",
    resultTwo: "SOME RESULT TEXT que10 opt-2",
    resultThree: "SOME RESULT TEXT que10 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 0,
    optionTwoMoneyAdded: 0,
    optionTwoMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 10,
  },
  {
    note: "Your child's class is going on a field trip to the natural history museum. The trip costs $15.",
    optionOne: "PAY THE MONEY",
    optionTwo: "DON'T PAY",
    optionThree: "",
    resultOne: "SOME RESULT TEXT que11 opt-1",
    resultTwo: "SOME RESULT TEXT que11 opt-2",
    resultThree: "SOME RESULT TEXT que11 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 15,
    optionTwoMoneyAdded: 0,
    optionTwoMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 11,
  },
  {
    note: "Two bills are due today.",
    optionOne: "PAY CELLPHONE BILL ($75)",
    optionTwo: "PAY CAR INSURANCE ($100)",
    optionThree: "PAY THEM BOTH ($175)",
    resultOne: "SOME RESULT TEXT que12 opt-1",
    resultTwo: "SOME RESULT TEXT que12 opt-2",
    resultThree: "SOME RESULT TEXT que12 opt-3",
    moneyAdded: 0, //some func that will set the amt in the option clicked
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 75,
    optionTwoMoneyAdded: 0,
    optionTwoMoneyRemoved: 100,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 175,
    id: 12,
  },
];

let secondShiftArr = [
  {
    note: "One of your co-workers has gotten seriously ill. Because your company doesn’t offer sick days, everyone is contributing $20 to help her out.",
    optionOne: "PITCH IN",
    optionTwo: "SAY YOU FORGOT YOUR WALLET",
    optionThree: "",
    resultOne: "void 1",
    resultTwo: "void 2",
    resultThree: "void 3",
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 0,
    optionTwoMoneyAdded: 0,
    optionTwoMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 1,
  },
  {
    note: "A family friend sends your child a card. Inside is $10.",
    optionOne: "GIVE YOUR CHILD THE $10",
    optionTwo: "KEEP THE $10",
    optionThree: "",
    resultOne: "void que2 opt-1",
    resultTwo: "void que2 opt-2",
    resultThree: "void que2 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 0,
    optionTwoMoneyAdded: 10,
    optionTwoMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 2,
  },
  {
    note: "Your best friend from childhood is getting married, and they want you to be in the wedding. The only problem: It's in another state.",
    optionOne: "FLY TO THE WEDDING ($350)",
    optionTwo: "SAY YOU CAN'T GO",
    optionThree: "",
    resultOne: "SOME RESULT TEXT que-3 opt-1",
    resultTwo: "SOME RESULT TEXT que-3 opt-2",
    resultThree: "SOME RESULT TEXT que-3 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 350,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 3,
  },
  {
    note: "You've been putting off doing laundry for weeks because you don't have a washer or dryer.",
    optionOne: "GO TO THE LAUNDROMAT ($30)",
    optionTwo: "ASK A FRIEND",
    optionThree: "WEAR DIRTY CLOTHES",
    resultOne: "SOME RESULT TEXT que4 opt-1",
    resultTwo: "SOME RESULT TEXT que4 opt-2",
    resultThree: "SOME RESULT TEXT que4 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 30,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 4,
  },
  {
    note: "The local community college is offering an online course in computer science, which could be your ticket to a higher paycheck. But the class costs $200.",
    optionOne: "SIGN UP ($200)",
    optionTwo: "MAYBE NEXT SEMESTER",
    optionThree: "",
    resultOne: "SOME RESULT TEXT que5 opt-1",
    resultTwo: "SOME RESULT TEXT que5 opt-2",
    resultThree: "SOME RESULT TEXT que5 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 200,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 5,
  },
  {
    note: "You're sure you weren't speeding, but the cop who gave you a ticket disagrees.",
    optionOne: "PAY IT OFF ($250)",
    optionTwo: "CONTEST IT IN COURT",
    optionThree: "",
    resultOne: "SOME RESULT TEXT que6 opt-1",
    resultTwo: "SOME RESULT TEXT que6 opt-2",
    resultThree: "SOME RESULT TEXT que6 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 250,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 100,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 6,
  },
  {
    note: "Your bathroom sink has a small leak that just became a big leak. Your landlord won't return your calls, and you can't put it off any longer.",
    optionOne: "CALL A PLUMBER ($150)",
    optionTwo: "TRY TO FIX IT YOURSELF",
    optionThree: "",
    resultOne: "SOME RESULT TEXT que7 opt-1",
    resultTwo: "SOME RESULT TEXT que7 opt-2",
    resultThree: "SOME RESULT TEXT que7 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 150,
    optionTwoMoneyAdded: 0,
    optionTwoMoneyRemoved: 50,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 7,
  },
  {
    note: "One of your co-workers has gotten seriously ill. Because your company doesn't offer sick days, everyone is contributing $20 to help her out.",
    optionOne: "PITCH IN",
    optionTwo: "SAY YOU FORGOT YOUR WALLET",
    optionThree: "",
    resultOne: "SOME RESULT TEXT que8 opt-1",
    resultTwo: "SOME RESULT TEXT que8 opt-2",
    resultThree: "SOME RESULT TEXT que8 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 20,
    optionTwoMoneyAdded: 0,
    optionTwoMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 8,
  },
  {
    note: "You come out of your house to discover that someone has siphoned the gas from your car. And you're already running late for work.",
    optionOne: "TAKE THE BUS",
    optionTwo: "CALL IN SICK",
    optionThree: "ASK A FRIEND FOR A RIDE",
    resultOne: "SOME RESULT TEXT que9 opt-1",
    resultTwo:
      "BCOS YOU CALLED IN SICK $50 WAS REMOVED FROM YOUR PAY-CHEQUE que9 opt-2",
    resultThree: "SOME RESULT TEXT que9 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 15,
    optionTwoMoneyAdded: 0,
    optionTwoMoneyRemoved: 50,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 9,
  },
  {
    note: "The repetitive work you do is taking its toll. Your back hurts so badly you can barely stand, and it's only the beginning of your shift.",
    optionOne: "SUBMIT A WORKER'S COMP CLAIM",
    optionTwo: "WORK THROUGH THE PAIN",
    optionThree: "TAKE THE DAY OFF",
    resultOne: "SOME RESULT TEXT que10 opt-1",
    resultTwo: "SOME RESULT TEXT que10 opt-2",
    resultThree: "SOME RESULT TEXT que10 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 0,
    optionTwoMoneyAdded: 0,
    optionTwoMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 10,
  },
  {
    note: "Your child's class is going on a field trip to the natural history museum. The trip costs $15.",
    optionOne: "PAY THE MONEY",
    optionTwo: "DON'T PAY",
    optionThree: "",
    resultOne: "SOME RESULT TEXT que11 opt-1",
    resultTwo: "SOME RESULT TEXT que11 opt-2",
    resultThree: "SOME RESULT TEXT que11 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 15,
    optionTwoMoneyAdded: 0,
    optionTwoMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 11,
  },
  {
    note: "Two bills are due today.",
    optionOne: "PAY CELLPHONE BILL ($75)",
    optionTwo: "PAY CAR INSURANCE ($100)",
    optionThree: "PAY THEM BOTH ($175)",
    resultOne: "SOME RESULT TEXT que12 opt-1",
    resultTwo: "SOME RESULT TEXT que12 opt-2",
    resultThree: "SOME RESULT TEXT que12 opt-3",
    moneyAdded: 0, //some func that will set the amt in the option clicked
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 75,
    optionTwoMoneyAdded: 0,
    optionTwoMoneyRemoved: 100,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 175,
    id: 12,
  },
];

let joinOurTeamArr = [
  {
    note: "One of your co-workers has gotten seriously ill. Because your company doesn’t offer sick days, everyone is contributing $20 to help her out.",
    optionOne: "PITCH IN",
    optionTwo: "SAY YOU FORGOT YOUR WALLET",
    optionThree: "",
    resultOne: "void 1",
    resultTwo: "void 2",
    resultThree: "void 3",
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 0,
    optionTwoMoneyAdded: 0,
    optionTwoMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 1,
  },
  {
    note: "A family friend sends your child a card. Inside is $10.",
    optionOne: "GIVE YOUR CHILD THE $10",
    optionTwo: "KEEP THE $10",
    optionThree: "",
    resultOne: "void que2 opt-1",
    resultTwo: "void que2 opt-2",
    resultThree: "void que2 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 0,
    optionTwoMoneyAdded: 10,
    optionTwoMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 2,
  },
  {
    note: "Your best friend from childhood is getting married, and they want you to be in the wedding. The only problem: It's in another state.",
    optionOne: "FLY TO THE WEDDING ($350)",
    optionTwo: "SAY YOU CAN'T GO",
    optionThree: "",
    resultOne: "SOME RESULT TEXT que-3 opt-1",
    resultTwo: "SOME RESULT TEXT que-3 opt-2",
    resultThree: "SOME RESULT TEXT que-3 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 350,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 3,
  },
  {
    note: "You've been putting off doing laundry for weeks because you don't have a washer or dryer.",
    optionOne: "GO TO THE LAUNDROMAT ($30)",
    optionTwo: "ASK A FRIEND",
    optionThree: "WEAR DIRTY CLOTHES",
    resultOne: "SOME RESULT TEXT que4 opt-1",
    resultTwo: "SOME RESULT TEXT que4 opt-2",
    resultThree: "SOME RESULT TEXT que4 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 30,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 4,
  },
  {
    note: "The local community college is offering an online course in computer science, which could be your ticket to a higher paycheck. But the class costs $200.",
    optionOne: "SIGN UP ($200)",
    optionTwo: "MAYBE NEXT SEMESTER",
    optionThree: "",
    resultOne: "SOME RESULT TEXT que5 opt-1",
    resultTwo: "SOME RESULT TEXT que5 opt-2",
    resultThree: "SOME RESULT TEXT que5 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 200,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 5,
  },
  {
    note: "You're sure you weren't speeding, but the cop who gave you a ticket disagrees.",
    optionOne: "PAY IT OFF ($250)",
    optionTwo: "CONTEST IT IN COURT",
    optionThree: "",
    resultOne: "SOME RESULT TEXT que6 opt-1",
    resultTwo: "SOME RESULT TEXT que6 opt-2",
    resultThree: "SOME RESULT TEXT que6 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 250,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 100,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 6,
  },
  {
    note: "Your bathroom sink has a small leak that just became a big leak. Your landlord won't return your calls, and you can't put it off any longer.",
    optionOne: "CALL A PLUMBER ($150)",
    optionTwo: "TRY TO FIX IT YOURSELF",
    optionThree: "",
    resultOne: "SOME RESULT TEXT que7 opt-1",
    resultTwo: "SOME RESULT TEXT que7 opt-2",
    resultThree: "SOME RESULT TEXT que7 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 150,
    optionTwoMoneyAdded: 0,
    optionTwoMoneyRemoved: 50,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 7,
  },
  {
    note: "One of your co-workers has gotten seriously ill. Because your company doesn't offer sick days, everyone is contributing $20 to help her out.",
    optionOne: "PITCH IN",
    optionTwo: "SAY YOU FORGOT YOUR WALLET",
    optionThree: "",
    resultOne: "SOME RESULT TEXT que8 opt-1",
    resultTwo: "SOME RESULT TEXT que8 opt-2",
    resultThree: "SOME RESULT TEXT que8 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 20,
    optionTwoMoneyAdded: 0,
    optionTwoMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 8,
  },
  {
    note: "You come out of your house to discover that someone has siphoned the gas from your car. And you're already running late for work.",
    optionOne: "TAKE THE BUS",
    optionTwo: "CALL IN SICK",
    optionThree: "ASK A FRIEND FOR A RIDE",
    resultOne: "SOME RESULT TEXT que9 opt-1",
    resultTwo:
      "BCOS YOU CALLED IN SICK $50 WAS REMOVED FROM YOUR PAY-CHEQUE que9 opt-2",
    resultThree: "SOME RESULT TEXT que9 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 15,
    optionTwoMoneyAdded: 0,
    optionTwoMoneyRemoved: 50,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 9,
  },
  {
    note: "The repetitive work you do is taking its toll. Your back hurts so badly you can barely stand, and it's only the beginning of your shift.",
    optionOne: "SUBMIT A WORKER'S COMP CLAIM",
    optionTwo: "WORK THROUGH THE PAIN",
    optionThree: "TAKE THE DAY OFF",
    resultOne: "SOME RESULT TEXT que10 opt-1",
    resultTwo: "SOME RESULT TEXT que10 opt-2",
    resultThree: "SOME RESULT TEXT que10 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 0,
    optionTwoMoneyAdded: 0,
    optionTwoMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 10,
  },
  {
    note: "Your child's class is going on a field trip to the natural history museum. The trip costs $15.",
    optionOne: "PAY THE MONEY",
    optionTwo: "DON'T PAY",
    optionThree: "",
    resultOne: "SOME RESULT TEXT que11 opt-1",
    resultTwo: "SOME RESULT TEXT que11 opt-2",
    resultThree: "SOME RESULT TEXT que11 opt-3",
    moneyAdded: 0,
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 15,
    optionTwoMoneyAdded: 0,
    optionTwoMoneyRemoved: 0,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 0,
    id: 11,
  },
  {
    note: "Two bills are due today.",
    optionOne: "PAY CELLPHONE BILL ($75)",
    optionTwo: "PAY CAR INSURANCE ($100)",
    optionThree: "PAY THEM BOTH ($175)",
    resultOne: "SOME RESULT TEXT que12 opt-1",
    resultTwo: "SOME RESULT TEXT que12 opt-2",
    resultThree: "SOME RESULT TEXT que12 opt-3",
    moneyAdded: 0, //some func that will set the amt in the option clicked
    moneyRemoved: 0,
    optionOneMoneyAdded: 0,
    optionOneMoneyRemoved: 75,
    optionTwoMoneyAdded: 0,
    optionTwoMoneyRemoved: 100,
    optionThreeMoneyAdded: 0,
    optionThreeMoneyRemoved: 175,
    id: 12,
  },
];

let currentQuestionArr;